inherit_gem:
  rubocop-rubomatic:
    - config/rubocop.yml
    - config/gemspec_on.yml

AllCops:
  Exclude:
    - 'examples/**/*'
    - 'spec/**/*'

Style/DocumentationMethod:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false
